spring:
  datasource:
    #第一数据源
    mysql:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://www.clcheng.asia:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&autoReconnect=true
      type: com.zaxxer.hikari.HikariDataSource
      username: root
      password: Ustb@701
      initialSize: 5
      maxActive: 10
      minIdle: 1
      maximumPoolSize: 10
      autoCommit: true
      poolName: HikariPool_mysql
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
    #第二数据源
    sqlserver:
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbcUrl: jdbc:sqlserver://www.clcheng.asia:1433;DatabaseName=test;trustServerCertificate=true
      type: com.zaxxer.hikari.HikariDataSource
      username: sa
      password: Ustb@701
      initialSize: 1
      maxActive: 1
      minIdle: 1
      maximumPoolSize: 1
      autoCommit: true
      poolName: HikariPool_sqlserver
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
    #第三数据源
    oracle:
      driverClassName: oracle.jdbc.OracleDriver
      jdbcUrl: jdbc:oracle:thin:@www.clcheng.asia:1521:FREE
      type: com.zaxxer.hikari.HikariDataSource
      username: system
      password: Ustb@701
      initialSize: 1
      maxActive: 1
      minIdle: 1
      maximumPoolSize: 1
      autoCommit: true
      poolName: HikariPool_oracle
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1 FROM DUAL

#      # 初始连接数
#      initialSize: 5
#      # 最小连接池数量
#      minIdle: 10
#      # 最大连接池数量
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000